minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  # Add packages to exclude from the minimum release age
  - "@mad-c/config"
trustPolicy: "no-downgrade"
preferFrozenLockfile: true
ignoreScripts: true
ignoreDepScripts: true
strictDepBuilds: true
engineStrict: false
ignorePnpmfile: true
blockExoticSubdeps: true
allowBuilds:
  # Add packages to allow running build scripts
  dprint: true
